name: Testing CI pipeline
on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v3

      - name: Print Hello
      - run: echo "Hellow World from faizan hahahahaha...." 